name: build-windows

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      # If you have runtime assets (images, json, etc.), include them via --add-data.
      # On Windows, the separator is ;  (on mac/linux it's :)
      - name: Build EXE (onefile)
        run: pyinstaller --noconsole --onefile --name CyberpunkRPCalc --hidden-import d20 main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: CyberpunkRPCalc-windows
          path: dist/CyberpunkRPCalc.exe
