name: build-windows
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pyinstaller
      - name: Build
        run: |
          pyinstaller --noconsole --onefile ^
            --name "CyberpunkRPCalc" ^
            --hidden-import d20 ^
            --add-data "assets;assets" ^
            main.py
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: CyberpunkRPCalc-windows
          path: dist/CyberpunkRPCalc.exe
